---
- name: Basic setup for Debian / Ubuntu
  hosts: all
  become: true
  tasks:
    - name: apt update
      become: yes
      ignore_unreachable: yes
      ansible.builtin.apt:
        update_cache: yes

    - name: apt upgrade
      become: yes
      ignore_unreachable: yes
      ansible.builtin.apt:
        upgrade: yes

    - name: Install required packages
      become: yes
      ignore_unreachable: yes
      ansible.builtin.apt:
        name:
          - git
          - build-essential
        state: present

- name: Install tkytel/lollipop
  hosts: all
  become: true
  tasks:
    - name: git clone tkytel/lollipop
      become: yes
      ignore_unreachable: yes
      ansible.builtin.git:
        repo: 'https://github.com/tkytel/lollipop.git'
        dest: /opt/lollipop
        clone: yes
        update: yes
        version: devel
      
    - name: Make tkytel/lollipop
      become: yes
      community.general.make:
        chdir: /opt/lollipop
      
    - name: Create a directory for lollipop's spool if it does not exist
      ansible.builtin.file:
        path: /var/spool/lollipop
        state: directory
        mode: '0755'
    
    - name: Copy lollipop executable
      become: yes
      ansible.builtin.copy:
        src: /opt/lollipop/lollipop
        dest: /usr/local/bin/lollipop
        mode: '0755'

- name: Deploy netplan config and apply for lollipopd's interface
  hosts: all
  become: yes
  vars:
    netplan_src: "../files/netplan/99-post.yaml"
    netplan_dest: "/etc/netplan/99-post.yaml"

  tasks:
    - block:
      - name: Ensure the directory /etc/netplan exists
        file:
          path: /etc/netplan
          state: directory
          owner: root
          group: root
          mode: '0755'

      - name: Copy netplan config to remote
        copy:
          src: "{{ netplan_src }}"
          dest: "{{ netplan_dest }}"
          owner: root
          group: root
          mode: '0644'
          backup: yes
        notify: Apply netplan
      
      when: ansible_facts['distribution'] == 'Ubuntu'

  handlers:
    - name: Apply netplan
      become: yes
      command: netplan apply
      register: netplan_apply
      changed_when: false
